/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultantConsultantNameIndexRouteImport } from './routes/consultant/$consultantName/index'
import { Route as ConsultantConsultantNameProjectProjectIdRouteImport } from './routes/consultant/$consultantName/project/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantConsultantNameIndexRoute =
  ConsultantConsultantNameIndexRouteImport.update({
    id: '/consultant/$consultantName/',
    path: '/consultant/$consultantName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultantConsultantNameProjectProjectIdRoute =
  ConsultantConsultantNameProjectProjectIdRouteImport.update({
    id: '/consultant/$consultantName/project/$projectId',
    path: '/consultant/$consultantName/project/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultant/$consultantName/': typeof ConsultantConsultantNameIndexRoute
  '/consultant/$consultantName/project/$projectId': typeof ConsultantConsultantNameProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultant/$consultantName': typeof ConsultantConsultantNameIndexRoute
  '/consultant/$consultantName/project/$projectId': typeof ConsultantConsultantNameProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultant/$consultantName/': typeof ConsultantConsultantNameIndexRoute
  '/consultant/$consultantName/project/$projectId': typeof ConsultantConsultantNameProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultant/$consultantName/'
    | '/consultant/$consultantName/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultant/$consultantName'
    | '/consultant/$consultantName/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/consultant/$consultantName/'
    | '/consultant/$consultantName/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultantConsultantNameIndexRoute: typeof ConsultantConsultantNameIndexRoute
  ConsultantConsultantNameProjectProjectIdRoute: typeof ConsultantConsultantNameProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/$consultantName/': {
      id: '/consultant/$consultantName/'
      path: '/consultant/$consultantName'
      fullPath: '/consultant/$consultantName/'
      preLoaderRoute: typeof ConsultantConsultantNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/$consultantName/project/$projectId': {
      id: '/consultant/$consultantName/project/$projectId'
      path: '/consultant/$consultantName/project/$projectId'
      fullPath: '/consultant/$consultantName/project/$projectId'
      preLoaderRoute: typeof ConsultantConsultantNameProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultantConsultantNameIndexRoute: ConsultantConsultantNameIndexRoute,
  ConsultantConsultantNameProjectProjectIdRoute:
    ConsultantConsultantNameProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
